name: Daily Notion Entry

on:
  schedule:
    - cron: "30 18 * * *" # runs every day at midnight UTC
  workflow_dispatch: # allows manual trigger from Actions tab

jobs:
  add-entry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python main.py
